# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\tapi.video\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x12\x43reateVideoRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"8\n\x12UpdateVideoRequest\x12\x10\n\x08old_path\x18\x01 \x01(\t\x12\x10\n\x08new_path\x18\x02 \x01(\t\"\"\n\x12\x44\x65leteVideoRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\":\n\x17\x43reateScreenShotRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tsite_path\x18\x02 \x01(\t\"=\n\x17UpdateScreenShotRequest\x12\x10\n\x08old_path\x18\x01 \x01(\t\x12\x10\n\x08new_path\x18\x02 \x01(\t\"\'\n\x17\x44\x65leteScreenShotRequest\x12\x0c\n\x04path\x18\x01 \x01(\t2\xcc\x03\n\x05Video\x12\x44\n\x0b\x43reateVideo\x12\x1d.api.video.CreateVideoRequest\x1a\x16.google.protobuf.Empty\x12O\n\x11\x43reateScreenShoot\x12\".api.video.CreateScreenShotRequest\x1a\x16.google.protobuf.Empty\x12O\n\x11UpdateScreenShoot\x12\".api.video.UpdateScreenShotRequest\x1a\x16.google.protobuf.Empty\x12O\n\x11\x44\x65leteScreenShoot\x12\".api.video.DeleteScreenShotRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\x0bUpdateVideo\x12\x1d.api.video.UpdateVideoRequest\x1a\x16.google.protobuf.Empty\x12\x44\n\x0b\x44\x65leteVideo\x12\x1d.api.video.DeleteVideoRequest\x1a\x16.google.protobuf.EmptyB2\n\x0b..api.videoP\x01Z!project-service/./api/video;videob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\013..api.videoP\001Z!project-service/./api/video;video'
  _globals['_CREATEVIDEOREQUEST']._serialized_start=55
  _globals['_CREATEVIDEOREQUEST']._serialized_end=89
  _globals['_UPDATEVIDEOREQUEST']._serialized_start=91
  _globals['_UPDATEVIDEOREQUEST']._serialized_end=147
  _globals['_DELETEVIDEOREQUEST']._serialized_start=149
  _globals['_DELETEVIDEOREQUEST']._serialized_end=183
  _globals['_CREATESCREENSHOTREQUEST']._serialized_start=185
  _globals['_CREATESCREENSHOTREQUEST']._serialized_end=243
  _globals['_UPDATESCREENSHOTREQUEST']._serialized_start=245
  _globals['_UPDATESCREENSHOTREQUEST']._serialized_end=306
  _globals['_DELETESCREENSHOTREQUEST']._serialized_start=308
  _globals['_DELETESCREENSHOTREQUEST']._serialized_end=347
  _globals['_VIDEO']._serialized_start=350
  _globals['_VIDEO']._serialized_end=810
# @@protoc_insertion_point(module_scope)
